### ISSUE TITLE
door postion absolute

### ISSUE THREAD

**Issue by Theo-denBlanken** [25953/Jquery#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
footer {
    position: absolute;
    width: 100%;
    left: 0;
    text-align: center;
    background-color: gray;
    padding: 10px;
  } 
```

URL: https://github.com/25953/Jquery/blob/master/style.css

Feedback: gaat de footer niet terug[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"b3b4c6e0f55d46bc1eacffb5773a1445fa0f8664","path":"style.css","reviewer":"Theo-denBlanken"}')

**Comment by KevinKranenburg** [comment]
position: absolute; veranderd door position: relative; 
de footer gaat nu terug naar beneden.

- Kevin Kranenburg
