### ISSUE TITLE
jQuery plugin ontbreekt:

### ISSUE THREAD

**Issue by Theo-denBlanken** [25953/Jquery#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/25953/Jquery/blob/master/style.css

Feedback: Voeg naar eigen inzicht een jQuery plugin aan deze pagina toe. Als je het beter vindt, dan mag je dat ook op een aparte pagina doen en vanuit jouw training daar een link naar leggen. 
Zie bijvoorbeeld ter inspiratie:

https://kenwheeler.github.io/slick/

https://speckyboy.com/free-jquery-plugins/

https://lokeshdhakar.com/projects/lightbox2/;

http://bla.hosts.ma-cloud.nl/20-mooie-jquery-plugins/

https://www.vandelaydesign.com/30-best-free-jquery-plugins/?utm_source=Vandelay&utm_campaign=4b50ff3c3c-RSS_EMAIL_CAMPAIGN&utm_medium=email&utm_term=0_64c66699ed-4b50ff3c3c-295182717[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"b3b4c6e0f55d46bc1eacffb5773a1445fa0f8664","path":"style.css","reviewer":"Theo-denBlanken"}')

**Comment by KevinKranenburg** [comment]
Jquery plugin toegevoegd.

-Kevin Kranenburg
